# Generated by Django 4.0.6 on 2022-10-26 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_alter_todotask_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todotask',
            name='date',
            field=models.DateField(),
        ),
    ]
