# Generated by Django 4.0.6 on 2022-11-11 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=255)),
                ('lastname', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('department', models.CharField(max_length=255)),
                ('phoneno', models.CharField(max_length=255)),
                ('gender', models.CharField(max_length=255)),
                ('dob', models.CharField(max_length=255)),
                ('qualification', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('pin', models.CharField(max_length=255)),
                ('state', models.CharField(max_length=255)),
                ('country', models.CharField(max_length=255)),
                ('status', models.CharField(max_length=255)),
            ],
        ),
    ]
